import styles from '../styles/Home.module.css'
import Head from 'next/head';
import { app } from '../firebaseConfig';
import { useEffect } from 'react';
import {
    getAuth,
    signInWithEmailAndPassword
} from 'firebase/auth'
import { useState } from 'react';
import { useRouter } from 'next/router';
export default function Register() {
    const auth = getAuth();

    const router = useRouter();
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    const signUp = () => {
        signInWithEmailAndPassword(auth, email, password)
            .then((response) => {
                console.log(response.user)
                sessionStorage.setItem('Token', response.user.accessToken);
                router.push('/home')
            })
            .catch(err => {
                alert('Cannot Log in')
            })
    }
    const register = () => {
        sessionStorage.removeItem('Token')
        router.push('/register')
      }

    useEffect(() => {
        let token = sessionStorage.getItem('Token')

        if(token){
            router.push('/login')
        }
    }, [])

    return (
        <div className={styles.container}>
            <Head>
                <title>Next CRUD AUTH</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>Login</h1>

                <input
                    placeholder='Email'
                    className={styles.inputBox}
                    onChange={(event) => setEmail(event.target.value)}
                    value={email}
                    type='email'
                />
                <input
                    placeholder='Password'
                    className={styles.inputBox}
                    onChange={(event) => setPassword(event.target.value)}
                    value={password}
                    type='password'
                />

                <button
                    className={styles.button}
                    onClick={signUp}
                >Sign In</button>
                <hr />
                <button
                    className={styles.button}
                    onClick={register}
                >register</button>
            </main>
        </div>
    )
}