import Head from 'next/head'
import { useEffect, useState } from 'react'
import {
  updateDoc,
  doc,
  getDoc,
} from 'firebase/firestore';
import styles from '../styles/Home.module.css'
import { database } from '../firebaseConfig';
import { useRouter } from 'next/router';
import {
  getAuth
}from 'firebase/auth';
export default function Home() {
  const [ans, setans] = useState(null);
  const auth = getAuth();
  const router = useRouter();
  const user = auth.currentUser;
  const user_data=doc(database,user?.email,user?.uid);
  const mainAns_data = doc(database, 'answer', 'q');
  
    
      const fetchFieldValue = async () => {
        try {
          
          const user_doc = await getDoc(user_data);
          const mainAns_doc = await getDoc(mainAns_data);
          const team_doc = await getDoc(team_data);

          const teamname = user_doc.get('name');
          
          const team_data = doc(database,"teams",teamname);
          console.log("hiii");
          if (mainAns_doc.exists()) {
            const mainAns = mainAns_doc.get('mq1');
            const userAns = user_doc.get('ans1');
            const teamMark = team_doc.get('q1');
            
            const mark = ()=>{
              if (userAns==mainAns){
                return true;
                
              }
              else {
                if(teamMark==true){
                  return true;
               }
               else{
                return false;
               }
            };
            }
            updateDoc(team_data,{
              q1: mark()
            }
            )
            
          } else {
            console.log('No such document');
          }
        } catch (error) {
          console.error('Error fetching field value:', error);
        }
      };

  const addData = () => {
      updateDoc(user_data, { 
        ans1: Number(ans)
    })
    fetchFieldValue()
      .then(() => {
        alert('Data Sent')
        router.push('/q2')
      })
      .catch((err) => {
        console.error(err);
      })
    }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Next CRUD AUTH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1>world's toughest question, what is 2+2?</h1>

        <input
          placeholder='enter your ans'
          className={styles.inputBox}
          type="number"
          value={ans}
          onChange={event => setans(event.target.value)}
        />
        {(
          <button
            className={styles.button}
            onClick={addData}
          >
            submit
          </button>
        )}
      </main>
    </div>
  )
}
